data = [
    {
        "name": "최민수",
        "age": 39,
        "position": "차장",
        "department": "경영",
        "skill": "데이터 분석",
        "education": "고졸",
        "years_at_company": 20,
        "hobby": "운동",
        "marital_status": "미혼",
        "certification": "정보처리기사",
        "award": "프로젝트 성과상",
        "address": "대구광역시"
    },
    {
        "name": "배수진",
        "age": 48,
        "position": "사원",
        "department": "인사",
        "skill": "엑셀",
        "education": "대학원졸",
        "years_at_company": 26,
        "hobby": "음악 감상",
        "marital_status": "미혼",
        "certification": "공인회계사",
        "award": "우수 직원상",
        "address": "서울특별시"
    },
    {
        "name": "한지훈",
        "age": 51,
        "position": "부장",
        "department": "경영",
        "skill": "회계",
        "education": "고졸",
        "years_at_company": 13,
        "hobby": "여행",
        "marital_status": "기혼",
        "certification": "마케팅 전문가",
        "award": "프로젝트 성과상",
        "address": "세종특별자치시"
    },
    {
        "name": "오지은",
        "age": 43,
        "position": "차장",
        "department": "IT",
        "skill": "마케팅",
        "education": "고졸",
        "years_at_company": 5,
        "hobby": "요리",
        "marital_status": "미혼",
        "certification": "컴퓨터 활용 능력",
        "award": "우수 직원상",
        "address": "대구광역시"
    },
    {
        "name": "송현아",
        "age": 49,
        "position": "차장",
        "department": "영업",
        "skill": "회계",
        "education": "고졸",
        "years_at_company": 10,
        "hobby": "요리",
        "marital_status": "미혼",
        "certification": "마케팅 전문가",
        "award": "고객 만족상",
        "address": "서울특별시"
    },
    {
        "name": "최민수",
        "age": 26,
        "position": "부장",
        "department": "경영",
        "skill": "마케팅",
        "education": "대졸",
        "years_at_company": 4,
        "hobby": "음악 감상",
        "marital_status": "기혼",
        "certification": "마케팅 전문가",
        "award": "최우수 팀상",
        "address": "강원도"
    },
    {
        "name": "배수진",
        "age": 44,
        "position": "과장",
        "department": "보안",
        "skill": "엑셀",
        "education": "고졸",
        "years_at_company": 23,
        "hobby": "여행",
        "marital_status": "미혼",
        "certification": "마케팅 전문가",
        "award": "프로젝트 성과상",
        "address": "강원도"
    },
    {
        "name": "오지은",
        "age": 37,
        "position": "대리",
        "department": "보안",
        "skill": "마케팅",
        "education": "대졸",
        "years_at_company": 29,
        "hobby": "여행",
        "marital_status": "기혼",
        "certification": "공인회계사",
        "award": "최우수 팀상",
        "address": "광주광역시"
    },
    {
        "name": "고진우",
        "age": 24,
        "position": "상무",
        "department": "IT",
        "skill": "데이터 분석",
        "education": "대학원졸",
        "years_at_company": 10,
        "hobby": "여행",
        "marital_status": "기혼",
        "certification": "정보처리기사",
        "award": "고객 만족상",
        "address": "울산광역시"
    },
    {
        "name": "문지영",
        "age": 34,
        "position": "과장",
        "department": "영업",
        "skill": "엑셀",
        "education": "고졸",
        "years_at_company": 9,
        "hobby": "독서",
        "marital_status": "미혼",
        "certification": "컴퓨터 활용 능력",
        "award": "고객 만족상",
        "address": "부산광역시"
    },
    {
        "name": "김철수",
        "age": 29,
        "position": "부장",
        "department": "보안",
        "skill": "프로그래밍",
        "education": "대졸",
        "years_at_company": 12,
        "hobby": "운동",
        "marital_status": "기혼",
        "certification": "정보처리기사",
        "award": "우수 직원상",
        "address": "서울특별시"
    },
    {
        "name": "이영희",
        "age": 30,
        "position": "대리",
        "department": "IT",
        "skill": "엑셀",
        "education": "대졸",
        "years_at_company": 5,
        "hobby": "여행",
        "marital_status": "기혼",
        "certification": "컴퓨터 활용 능력",
        "award": "최우수 팀상",
        "address": "부산광역시"
    },
    {
        "name": "정혜진",
        "age": 28,
        "position": "사원",
        "department": "영업",
        "skill": "데이터 분석",
        "education": "대학원졸",
        "years_at_company": 6,
        "hobby": "음악 감상",
        "marital_status": "미혼",
        "certification": "공인회계사",
        "award": "우수 직원상",
        "address": "서울특별시"
    },
    {
        "name": "강민호",
        "age": 40,
        "position": "부장",
        "department": "인사",
        "skill": "엑셀",
        "education": "고졸",
        "years_at_company": 18,
        "hobby": "요리",
        "marital_status": "기혼",
        "certification": "컴퓨터 활용 능력",
        "award": "고객 만족상",
        "address": "인천광역시"
    },
    {
        "name": "고진우",
        "age": 41,
        "position": "과장",
        "department": "경영",
        "skill": "회계",
        "education": "대졸",
        "years_at_company": 10,
        "hobby": "운동",
        "marital_status": "기혼",
        "certification": "마케팅 전문가",
        "award": "프로젝트 성과상",
        "address": "대구광역시"
    },
    {
        "name": "이영희",
        "age": 45,
        "position": "차장",
        "department": "영업",
        "skill": "데이터 분석",
        "education": "고졸",
        "years_at_company": 15,
        "hobby": "독서",
        "marital_status": "미혼",
        "certification": "정보처리기사",
        "award": "우수 직원상",
        "address": "부산광역시"
    },
    {
        "name": "문지영",
        "age": 25,
        "position": "상무",
        "department": "경영",
        "skill": "프로그래밍",
        "education": "대학원졸",
        "years_at_company": 13,
        "hobby": "음악 감상",
        "marital_status": "미혼",
        "certification": "마케팅 전문가",
        "award": "우수 직원상",
        "address": "인천광역시"
    },
    {
        "name": "배수진",
        "age": 49,
        "position": "상무",
        "department": "IT",
        "skill": "프로그래밍",
        "education": "대학원졸",
        "years_at_company": 8,
        "hobby": "요리",
        "marital_status": "기혼",
        "certification": "공인회계사",
        "award": "프로젝트 성과상",
        "address": "광주광역시"
    },
    {
        "name": "박지훈",
        "age": 36,
        "position": "대리",
        "department": "경영",
        "skill": "회계",
        "education": "대졸",
        "years_at_company": 9,
        "hobby": "독서",
        "marital_status": "미혼",
        "certification": "컴퓨터 활용 능력",
        "award": "우수 직원상",
        "address": "울산광역시"
    },
    {
        "name": "한지훈",
        "age": 57,
        "position": "대리",
        "department": "경영",
        "skill": "데이터 분석",
        "education": "대학원졸",
        "years_at_company": 18,
        "hobby": "요리",
        "marital_status": "기혼",
        "certification": "공인회계사",
        "award": "프로젝트 성과상",
        "address": "울산광역시"
    },
    {
        "name": "홍진호",
        "age": 31,
        "position": "사원",
        "department": "보안",
        "skill": "엑셀",
        "education": "고졸",
        "years_at_company": 10,
        "hobby": "요리",
        "marital_status": "미혼",
        "certification": "정보처리기사",
        "award": "프로젝트 성과상",
        "address": "인천광역시"
    },
    {
        "name": "정혜진",
        "age": 26,
        "position": "부장",
        "department": "인사",
        "skill": "엑셀",
        "education": "고졸",
        "years_at_company": 17,
        "hobby": "독서",
        "marital_status": "기혼",
        "certification": "공인회계사",
        "award": "최우수 팀상",
        "address": "울산광역시"
    },
    {
        "name": "문지영",
        "age": 56,
        "position": "대리",
        "department": "영업",
        "skill": "프로그래밍",
        "education": "고졸",
        "years_at_company": 11,
        "hobby": "독서",
        "marital_status": "미혼",
        "certification": "컴퓨터 활용 능력",
        "award": "최우수 팀상",
        "address": "대전광역시"
    },
    {
        "name": "김지수",
        "age": 56,
        "position": "차장",
        "department": "IT",
        "skill": "회계",
        "education": "대학원졸",
        "years_at_company": 9,
        "hobby": "운동",
        "marital_status": "기혼",
        "certification": "공인회계사",
        "award": "우수 직원상",
        "address": "울산광역시"
    }
]
